/*
 * swaggerpetstore_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package SwaggerPetstoreClient

import(
	"swaggerpetstore_lib/configuration_pkg"
	"swaggerpetstore_lib/user_pkg"
	"swaggerpetstore_lib/store_pkg"
	"swaggerpetstore_lib/pet_pkg"
)


/*
 * Interface for the SWAGGERPETSTORE_IMPL
 */
type SWAGGERPETSTORE interface {
    User()                  user_pkg.USER
    Store()                 store_pkg.STORE
    Pet()                   pet_pkg.PET
    Configuration()         configuration_pkg.CONFIGURATION
}

/*
 * Factory for the SWAGGERPETSTORE interface returning SWAGGERPETSTORE_IMPL
 */
func NewSWAGGERPETSTORE() SWAGGERPETSTORE {
    swaggerPetstoreClient := new(SWAGGERPETSTORE_IMPL)
    swaggerPetstoreClient.config = configuration_pkg.NewCONFIGURATION()

    return swaggerPetstoreClient
}
